version: '3.8'

services:
  server:
    container_name: vites-dev
    image: ignis-server:dev
    ports:
      - "8082:8080" # Ignis Dev
    environment:
      - GIN_MODE=debug
      - PORT=${PORT:-8080}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-vites_user}
      - DB_PASSWORD=${DB_PASSWORD:-vites_secure_pass_2026}
      - DB_NAME=${DB_NAME:-vites_db}
      - FIREBASE_CREDENTIALS_PATH=/root/firebase-adminsdk.json
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - DOMAINS=${DOMAINS:-dev.vites.iamsorry.in}
      - FIREBASE_CREDENTIALS_JSON=${FIREBASE_CREDENTIALS_JSON}
    depends_on:
      - db
    networks:
      - ignis-dev-network
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: vites-dev-db
    environment:
      POSTGRES_USER: vites_user
      POSTGRES_PASSWORD: vites_secure_pass_2026
      POSTGRES_DB: vites_db
    volumes:
      - ignis_dev_pg_data:/var/lib/postgresql/data
    networks:
      - ignis-dev-network
    restart: unless-stopped

volumes:
  ignis_dev_pg_data:

networks:
  ignis-dev-network:
    driver: bridge
