version: '3.8'

services:
  server:
    container_name: ignis-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8082:8080" # Ignis Dev
    env_file:
      - ./server/.env
    environment:
      - GIN_MODE=debug
      - DB_HOST=db
      - DB_PORT=5432
      - FIREBASE_CREDENTIALS_PATH=/root/firebase-adminsdk.json
    depends_on:
      - db
    volumes:
      - ./server/firebase-adminsdk.json:/root/firebase-adminsdk.json
    networks:
      - ignis-dev-network
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: ignis-dev-db
    environment:
      POSTGRES_USER: ${DB_USER:-ignis_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-local_pass}
      POSTGRES_DB: ${DB_NAME:-ignis_db}
    volumes:
      - ignis_dev_pg_data:/var/lib/postgresql/data
    networks:
      - ignis-dev-network
    restart: unless-stopped

volumes:
  ignis_dev_pg_data:

networks:
  ignis-dev-network:
    driver: bridge
