# Build Stage
FROM golang:1.25-alpine AS builder

# Install git for fetching dependencies
RUN apk add --no-cache git

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build args
ARG VERSION=dev

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.Version=${VERSION}" -o vites-server ./cmd/server

# Run Stage
FROM alpine:latest  

RUN apk --no-cache add ca-certificates curl

WORKDIR /root/

# Copy the Pre-built binary from the builder stage
COPY --from=builder /app/vites-server .

# Copy migrations
COPY --from=builder /app/db ./db

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./vites-server"]
