// File generated by FlutterFire CLI and manually cleaned up for Ignis Core.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYC-0opeF4QOttCWXoUxKOapCN86e1f-k',
    appId: '1:994865471277:android:00ee3cfde1ca352dadbda4',
    messagingSenderId: '994865471277',
    projectId: 'vivaah-ignis-dev',
    storageBucket: 'vivaah-ignis-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6XFdNO3BRg2oQ5tF6jhFH8Vbhzz1kkBM',
    appId: '1:994865471277:ios:d65167d377ab9021adbda4',
    messagingSenderId: '994865471277',
    projectId: 'vivaah-ignis-dev',
    storageBucket: 'vivaah-ignis-dev.firebasestorage.app',
    iosBundleId: 'com.ignis.vivaah.dev',
  );
}
