// File generated by FlutterFire CLI and manually cleaned up for Ignis Core.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgtl67m885k5O5IrcY0T4d05-KM4_ncE',
    appId: '1:892343603637:android:0eefefa9e34528c83889fc',
    messagingSenderId: '892343603637',
    projectId: 'vivaah-ignis-prod',
    storageBucket: 'vivaah-ignis-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJh5qecD2bpURs4Twe2z5WXiEZpU_IBs',
    appId: '1:892343603637:ios:1b050c02b0b179743889fc',
    messagingSenderId: '892343603637',
    projectId: 'vivaah-ignis-prod',
    storageBucket: 'vivaah-ignis-prod.firebasestorage.app',
    iosBundleId: 'com.ignis.vivaah',
  );
}
